#!/usr/bin/env bash
# making a story around the /etc/passwd file

while IFS= read -r line; do
  	awk -F':' '{print "The user " $1 " is part of the " $4 " gang, lives in " $6 " and rides " $7 ". " $3 "'\''s place is protected by the passcode " $2 ", more info about the user here: " $5}' <<< "$line"
done < "/etc/passwd"
